FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# GymAry V1

GymAry is an API to manage the activity of a gym.

## Members Collection [/members]

### List All Members [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "nombre": "Juan",
                "apellidos": "Fernández García",
                "dni": "83762084Y",
                "dirección": "Calle Roca Nº2"
                "ciudad": "A Coruña",
                "codigo postal": 15007
                "email": "juan.fernandez@gmail.com"
                "telefono": 686745367
            },
            {
                "id": 2,
                "nombre": "Rosa",
                "apellidos": "Rey Varela",
                "dni": "73645299J",
                "dirección": "Calle Azul Nº50"
                "ciudad": "A Coruña",
                "codigo postal": 15009
                "email": "rosareyva@gmail.com"
                "telefono": 656438892
            }
        ]
        

### Create a New Question [POST]

You may create your own question using this action. It takes a JSON
object containing a question and a collection of answers in the
form of choices.

+ Request (application/json)

        {
            "question": "Favourite programming language?",
            "choices": [
                "Swift",
                "Python",
                "Objective-C",
                "Ruby"
            ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "question": "Favourite programming language?",
                "published_at": "2015-08-05T08:40:51.620Z",
                "choices": [
                    {
                        "choice": "Swift",
                        "votes": 0
                    }, {
                        "choice": "Python",
                        "votes": 0
                    }, {
                        "choice": "Objective-C",
                        "votes": 0
                    }, {
                        "choice": "Ruby",
                        "votes": 0
                    }
                ]
            }
            
## Member [/members/{member_id}]

+ Parameters
    + member_id (number) - ID of the member in the form of an integer

### Get member [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "nombre": "Rosa",
            "apellidos": "Rey Varela",
            "dni": "73645299J",
            "dirección": "Calle Azul Nº50"
            "ciudad": "A Coruña",
            "codigo postal": 15009
            "email": "rosareyva@gmail.com"
            "telefono": 656438892
        }