FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# GymAry V1

GymAry is an API to manage the activity of a gym.

## Members Collection [/members]

### List All Members [GET]

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "nombre": "Juan",
                "apellidos": "Fernández García",
                "dni": "83762084Y",
                "dirección": "Calle Roca Nº2"
                "ciudad": "A Coruña",
                "codigo postal": 15007,
                "email": "juan.fernandez@gmail.com",
                "telefono": 686745367,
                "actividades":
                    [
                        {
                            "id": 1,
                            "nombre": "crossfit",
                            "horario":
                                [
                                    {
                                        "dia": "lunes",
                                        "hora": ["11:30","18:00"]
                                    },
                                    {
                                        "dia": "jueves",
                                        "hora": ["17:30"]
                                    }
                                ]
                        }
                    ]
            },
            {
                "id": 2,
                "nombre": "Rosa",
                "apellidos": "Rey Varela",
                "dni": "73645299J",
                "dirección": "Calle Azul Nº50"
                "ciudad": "A Coruña",
                "codigo postal": 15009,
                "email": "rosareyva@gmail.com",
                "telefono": 656438892,
                "actividades": []
            }
        ]

### Get member [GET/members/{member_id}]
+ Parameters
    + member_id (number) - ID of the member in the form of an integer

+ Response 200 (application/json)

        {
            "id": 2,
            "nombre": "Rosa",
            "apellidos": "Rey Varela",
            "dni": "73645299J",
            "dirección": "Calle Azul Nº50"
            "ciudad": "A Coruña",
            "codigo postal": 15009,
            "email": "rosareyva@gmail.com",
            "telefono": 656438892,
            "actividades": []
        }
        
### Sign up a new member [POST]

+ Request (application/json)

        {
            "nombre": "Marcos",
            "apellidos": "Taboada Fraga",
            "dni": "73649812I",
            "dirección": "Calle Cruz Nº109"
            "ciudad": "A Coruña",
            "codigo postal": 15008,
            "email": "marcos.tabo@gmail.com",
            "telefono": 677425109,
            "actividades":
                [
                    {
                        "id": 1,
                        "nombre": "crossfit",
                        "horario":
                            [
                                {
                                    "dia": "lunes",
                                    "hora": ["11:30","18:00"]
                                },
                                {
                                    "dia": "jueves",
                                    "hora": ["17:30"]
                                }
                            ]
                    },
                    {
                        "id": 2,
                        "nombre": "calistenia",
                        "horario":
                            [
                                {
                                    "dia": "miercoles",
                                    "hora": ["17:00"]
                                }
                            ]
                    }
                ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /members/3

    + Body

            {
                "id": 3,
                "nombre": "Marcos",
                "apellidos": "Taboada Fraga",
                "dni": "73649812I",
                "dirección": "Calle Cruz Nº109"
                "ciudad": "A Coruña",
                "codigo postal": 15008,
                "email": "marcos.tabo@gmail.com",
                "telefono": 677425109,
                "actividades":
                    [
                        {
                            "id": 1,
                            "nombre": "crossfit",
                            "dias": ["lunes","jueves"],
                            "hora": "11:30"
                        },
                        {
                            "id": 2,
                            "nombre": "calistenia",
                            "dias": ["miercoles"],
                            "hora": "17:00"
                        }
                    ]
            }